# CMake generated Testfile for 
# Source directory: Q:/Kitware/gccxml/GCC_XML/Testing
# Build directory: Q:/Kitware/gccxml-build/GCC_XML/Testing
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(gxConfiguration.cxx "Q:/Kitware/gccxml-build/bin/gccxml" "-IQ:/Kitware/gccxml-build/GCC_XML/GXFront" "-IQ:/Kitware/gccxml-build/GCC_XML" "-IQ:/Kitware/gccxml-build/GCC_XML/GXFront" "-IQ:/Kitware/gccxml/GCC_XML/GXFront" "Q:/Kitware/gccxml/GCC_XML/GXFront/gxConfiguration.cxx" "-fxml=gxConfiguration.cxx.gcc.xml")
add_test(gxConfiguration.h "Q:/Kitware/gccxml-build/bin/gccxml" "-IQ:/Kitware/gccxml-build/GCC_XML/GXFront" "-IQ:/Kitware/gccxml-build/GCC_XML" "-IQ:/Kitware/gccxml-build/GCC_XML/GXFront" "-IQ:/Kitware/gccxml/GCC_XML/GXFront" "Q:/Kitware/gccxml/GCC_XML/GXFront/gxConfiguration.h" "-fxml=gxConfiguration.h.gcc.xml")
add_test(gxDocumentation.cxx "Q:/Kitware/gccxml-build/bin/gccxml" "-IQ:/Kitware/gccxml-build/GCC_XML/GXFront" "-IQ:/Kitware/gccxml-build/GCC_XML" "-IQ:/Kitware/gccxml-build/GCC_XML/GXFront" "-IQ:/Kitware/gccxml/GCC_XML/GXFront" "Q:/Kitware/gccxml/GCC_XML/GXFront/gxDocumentation.cxx" "-fxml=gxDocumentation.cxx.gcc.xml")
add_test(gxDocumentation.h "Q:/Kitware/gccxml-build/bin/gccxml" "-IQ:/Kitware/gccxml-build/GCC_XML/GXFront" "-IQ:/Kitware/gccxml-build/GCC_XML" "-IQ:/Kitware/gccxml-build/GCC_XML/GXFront" "-IQ:/Kitware/gccxml/GCC_XML/GXFront" "Q:/Kitware/gccxml/GCC_XML/GXFront/gxDocumentation.h" "-fxml=gxDocumentation.h.gcc.xml")
add_test(gxFlagsParser.cxx "Q:/Kitware/gccxml-build/bin/gccxml" "-IQ:/Kitware/gccxml-build/GCC_XML/GXFront" "-IQ:/Kitware/gccxml-build/GCC_XML" "-IQ:/Kitware/gccxml-build/GCC_XML/GXFront" "-IQ:/Kitware/gccxml/GCC_XML/GXFront" "Q:/Kitware/gccxml/GCC_XML/GXFront/gxFlagsParser.cxx" "-fxml=gxFlagsParser.cxx.gcc.xml")
add_test(gxFlagsParser.h "Q:/Kitware/gccxml-build/bin/gccxml" "-IQ:/Kitware/gccxml-build/GCC_XML/GXFront" "-IQ:/Kitware/gccxml-build/GCC_XML" "-IQ:/Kitware/gccxml-build/GCC_XML/GXFront" "-IQ:/Kitware/gccxml/GCC_XML/GXFront" "Q:/Kitware/gccxml/GCC_XML/GXFront/gxFlagsParser.h" "-fxml=gxFlagsParser.h.gcc.xml")
add_test(gxFront.cxx "Q:/Kitware/gccxml-build/bin/gccxml" "-IQ:/Kitware/gccxml-build/GCC_XML/GXFront" "-IQ:/Kitware/gccxml-build/GCC_XML" "-IQ:/Kitware/gccxml-build/GCC_XML/GXFront" "-IQ:/Kitware/gccxml/GCC_XML/GXFront" "Q:/Kitware/gccxml/GCC_XML/GXFront/gxFront.cxx" "-fxml=gxFront.cxx.gcc.xml")
add_test(gxSystemTools.cxx "Q:/Kitware/gccxml-build/bin/gccxml" "-IQ:/Kitware/gccxml-build/GCC_XML/GXFront" "-IQ:/Kitware/gccxml-build/GCC_XML" "-IQ:/Kitware/gccxml-build/GCC_XML/GXFront" "-IQ:/Kitware/gccxml/GCC_XML/GXFront" "Q:/Kitware/gccxml/GCC_XML/GXFront/gxSystemTools.cxx" "-fxml=gxSystemTools.cxx.gcc.xml")
add_test(gxSystemTools.h "Q:/Kitware/gccxml-build/bin/gccxml" "-IQ:/Kitware/gccxml-build/GCC_XML/GXFront" "-IQ:/Kitware/gccxml-build/GCC_XML" "-IQ:/Kitware/gccxml-build/GCC_XML/GXFront" "-IQ:/Kitware/gccxml/GCC_XML/GXFront" "Q:/Kitware/gccxml/GCC_XML/GXFront/gxSystemTools.h" "-fxml=gxSystemTools.h.gcc.xml")
add_test(TestFullPathInclude.cxx "Q:/Kitware/gccxml-build/bin/gccxml" "-IQ:/Kitware/gccxml-build/GCC_XML/GXFront" "-IQ:/Kitware/gccxml-build/GCC_XML" "-IQ:/Kitware/gccxml-build/GCC_XML/GXFront" "-IQ:/Kitware/gccxml/GCC_XML/GXFront" "Q:/Kitware/gccxml-build/GCC_XML/Testing/TestFullPathInclude.cxx" "-fxml=TestFullPathInclude.cxx.gcc.xml")
add_test(TestUsualInclude.cxx "Q:/Kitware/gccxml-build/bin/gccxml" "-IQ:/Kitware/gccxml-build/GCC_XML/GXFront" "-IQ:/Kitware/gccxml-build/GCC_XML" "-IQ:/Kitware/gccxml-build/GCC_XML/GXFront" "-IQ:/Kitware/gccxml/GCC_XML/GXFront" "Q:/Kitware/gccxml/GCC_XML/Testing/TestUsualInclude.cxx" "-fxml=TestUsualInclude.cxx.gcc.xml")
